name: coin_aggregator
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  bloc: ^8.0.3
  cupertino_icons: ^1.0.5
  dio: ^4.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^2.2.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get_it: ^7.2.0
  go_router: ^0.0.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  retrofit: ^3.0.1+1


dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  retrofit_generator: ^4.0.1
  very_good_analysis: ^3.0.0
  
flutter:
  uses-material-design: true
  generate: true
